apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: chess
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: chess
spec:
  resources:
    requests:
      storage: 2Gi 
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
