apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: chess
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vmi2302294.contaboserver.net
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: chess
spec:
  resources:
    requests:
      storage: 2Gi 
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
