apiVersion: v1
kind: Service
metadata:
  name: chess-backend
  namespace: chess
spec:
  type: NodePort
  selector:
    app: chess-backend-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080

