apiVersion: v1
kind: Service
metadata:
  name: chess-backend
  namespace: chess
spec:
  loadBalancerPolicy: ip_hash
  sessionAffinity: ClientIP
  selector:
    app: chess-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
