apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  namespace: chess
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-express-deployment
  template:
    metadata:
      labels:
        app: mongo-express-deployment
    spec:
      containers:
      - name: mongo-express-deployment
        image: mongo-express
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: "user"
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: "password"
          - name: ME_CONFIG_MONGODB_SERVER
            value: "mongo"

