apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-deployment
  namespace: chess
spec:
  selector:
    matchLabels:
      app: mongo-deployment
  serviceName: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-deployment
    spec:
      containers:
      - name: mongo-deployment
        image: mongo:latest 
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo
          mountPath: /data/db
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "user"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "password"
      volumes:
      - name: mongo
        persistentVolumeClaim:
          claimName: chess-pvc
