apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chess-pv
  namespace: chess
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 50Gi