# pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-chess
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/chess"   # ye path tere node par hona chahiye
  persistentVolumeReclaimPolicy: Retain