apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chess-pvc
  namespace: chess
spec:
  resources:
    requests:
      storage: 50Gi 
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
