apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-deployment
  namespace: chess
spec:
  selector:
    matchLabels:
      app: redis-deployment
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-deployment
    spec:
      containers:
      - name: redis-deployment
        image: redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis
          mountPath: /data
      volumes:
      - name: redis
        persistentVolumeClaim:
          claimName: chess-pvc
