version: v4
volumes:
    mongo_data:
    kafka_data:

services:
    redis:
        image: redis:latest
        ports:
            - 6379:6379

    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=user
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - mongo_data:/data/db

    mongo-express:
        image: mongo-express
        ports:
            - 8083:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=user
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_SERVER=mongodb

    nginx:
        image: 'nginx:latest'
        hostname: nginx
        container_name: nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
